---
abstract: 'Delight Light Highlight the POD'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.132660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Text-Color-Delight
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Pod::Text::Color::Delight:
    file: lib/Pod/Text/Color/Delight.pm
    version: 0.06
requires:
  Pod::Text::Color: 2.07
  Syntax::Highlight::Perl::Improved: 0
  Term::ANSIColor: 4.02
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/moznion/Pod-Text-Color-Delight/issues
  homepage: https://github.com/moznion/Pod-Text-Color-Delight
  repository: git://github.com/moznion/Pod-Text-Color-Delight
version: 0.06
